global:
  scrape_interval: 5s

scrape_configs:
  - job_name: open5gs-mmed
    static_configs:
#      - targets: ["127.0.0.2:9090"]
      - targets: ["172.16.16.104:9092"]
  - job_name: open5gs-smfd
    static_configs:
#      - targets: ["127.0.0.4:9090"]
      - targets: ["172.16.16.104:9094"]
  - job_name: open5gs-amfd
    static_configs:
#      - targets: ["127.0.0.5:9090"]
      - targets: ["172.16.16.104:9095"]
  - job_name: open5gs-upfd
    static_configs:
#      - targets: ["127.0.0.7:9090"]
      - targets: ["172.16.16.104:9097"]
  - job_name: open5gs-pcfd
    static_configs:
#      - targets: ["127.0.0.13:9090"]
      - targets: ["172.16.16.104:9093"]